CREATE TABLE PERFILES (
Perf_Codigo     INTEGER        NOT NULL,
Perf_Nombre     VARCHAR(50)    NOT NULL,
CONSTRAINT PK_Perf_Codigo PRIMARY KEY (Perf_Codigo),
CONSTRAINT UK_Perf_Nombre UNIQUE (Perf_Nombre));

CREATE TABLE USUARIOS (
Usu_Codigo      INTEGER        NOT NULL,
PERF_CODIGO     INTEGER        NOT NULL,
Usu_Nombre      VARCHAR(50)    NOT NULL,
Usu_Apellido    VARCHAR(50)    NOT NULL,
Usu_NomAcceso   VARCHAR(50)    NOT NULL,
Usu_Contrasena  VARCHAR(50)    NOT NULL,
Usu_Correo      VARCHAR(50)    NOT NULL,
CONSTRAINT PK_Usu_Codigo PRIMARY KEY (Usu_Codigo),
CONSTRAINT UK_NomAcceso UNIQUE (Usu_NomAcceso),
CONSTRAINT UK_Usu_Correo UNIQUE (Usu_Correo));

CREATE TABLE PRODUCTOS (
PROD_ID         INTEGER     NOT NULL,
USU_CODIGO      INTEGER     NOT NULL,
FAMI_CODI       INTEGER     NOT NULL,
PROD_VOL        INTEGER     NOT NULL,
PROD_PESO       INTEGER     NOT NULL,
PROD_LOTE       INTEGER     NOT NULL,
PROD_FVEN       DATE        NOT NULL,
PROD_FELAB      DATE,
PROD_NOMBRE     VARCHAR(50) NOT NULL,
PROD_ESTIBA     VARCHAR(2)  NOT NULL,
PROD_SEGMETAC   VARCHAR(2)  NOT NULL,
PROD_STKMIN     INTEGER     NOT NULL,
PROD_STKTOTAL   INTEGER     NOT NULL,
PROD_PRECIO     BINARY_DOUBLE      NOT NULL,
CONSTRAINT PK_PROD_ID PRIMARY KEY (PROD_ID),
CONSTRAINT UK_PROD_NOMBRE UNIQUE (PROD_NOMBRE));

CREATE TABLE FAMILIAS (
FAMI_CODI       INTEGER     NOT NULL,
FAMI_INCOMPAT   varchar(2)     NOT NULL,
FAMI_NOMBRE     VARCHAR(50) NOT NULL,
FAMI_DESCRIP    VARCHAR(100),
CONSTRAINT PK_FAMI_CODI PRIMARY KEY (FAMI_CODI),
CONSTRAINT UK_FAMI_NOMBRE UNIQUE (FAMI_NOMBRE));

CREATE TABLE RENGLONESPEDIDOS (
PED_ID          INTEGER     NOT NULL,
RENPED_NRO      INTEGER     NOT NULL,
RENPED_CANT     INTEGER     NOT NULL);

CREATE TABLE MOVIMIENTOS (
MOV_FECHA       DATE        NOT NULL,
MOV_CANTIDAD    INTEGER     NOT NULL,
MOV_DESCRIPCION VARCHAR(100),
MOV_PROD        VARCHAR(50) NOT NULL,
MOV_TIPO        VARCHAR(50) NOT NULL);

CREATE TABLE ALMACENAMIENTOS (
ALMA_ID             INTEGER     NOT NULL,
LOC_ID              INTEGER     NOT NULL,
ALMA_VOLUMEN        INTEGER     NOT NULL,
ALMA_DESCRIPCION    VARCHAR(100)NOT NULL,
ALMA_COSTOOP        BINARY_DOUBLE      NOT NULL,
ALMA_CAPESTIBA      INTEGER     NOT NULL,
ALMA_CAPPESO        INTEGER     NOT NULL,
CONSTRAINT PK_ALMA_ID PRIMARY KEY (ALMA_ID));

CREATE TABLE LOCALES (
LOC_ID          INTEGER     NOT NULL,
CIU_ID          INTEGER     NOT NULL,
LOC_DESCRIP     VARCHAR(100)NOT NULL,
LOC_DIRECCION   VARCHAR(100)NOT NULL,
LOC_TIPO        VARCHAR(50) NOT NULL,
CONSTRAINT PK_LOC_ID PRIMARY KEY (LOC_ID));

CREATE TABLE CIUDADES (
CIU_NOMBRE      VARCHAR(50) NOT NULL,
CIU_ID          INTEGER     NOT NULL,
CONSTRAINT PK_CIU_ID PRIMARY KEY (CIU_ID));

CREATE TABLE PEDIDOS (
PED_ID              INTEGER     NOT NULL,
USU_CODIGO          INTEGER     NOT NULL,
PED_ESTADO          varchar(2)  NOT NULL,
PED_FEC_ESTIM_ENT   DATE        NOT NULL,
PED_FECHA           DATE        NOT NULL,
CONSTRAINT PK_PED_ID PRIMARY KEY (PED_ID));

CREATE TABLE RECEPCION (
REC_CODIGO          INTEGER     NOT NULL,
USU_CODIGO          INTEGER     NOT NULL,
REC_FECHA           DATE        NOT NULL,
REC_COMENTARIO      VARCHAR(100),
CONSTRAINT PK_REC_CODIGO PRIMARY KEY (REC_CODIGO));
